Feature: Conditional input interview transcript
joshsoftware/lingo.ai pull request #62
Opened 2024-12-30 11:45 UTC by Abhishek-Jain-1925

Workdone is as follows -
1. Conditionally accepting Transcript File and Transcript File URL for ArCruit Result Generation

2025-01-07 06:11 UTC, AjinkyaASK requested changes
Requested suggestions and changes inline.

2025-01-07 06:11 UTC, AjinkyaASK commented on service/utils/constants.py
Need to rewrite the 'QNA_DIFFCULTY_LEVEL_RATING_FIND_PROMPT' prompt, as discussed.

2025-01-13 04:39 UTC, Abhishek-Jain-1925 commented on app/migrations/0008_sudden_switch.sql
> +	"id" text PRIMARY KEY NOT NULL,
As we are storing the IDs in AlphaNumeric Format so that type text is used

2025-01-13 04:39 UTC, Abhishek-Jain-1925 commented on app/migrations/0008_sudden_switch.sql
> +	"user_id" text NOT NULL,
As we are storing the IDs in AlphaNumeric Format so that type text is used

2025-01-13 04:44 UTC, Abhishek-Jain-1925 commented on app/src/components/AiCruitForm.tsx
> +        "Your Details Received successfully! Once completed, you can visit the listing page"
Done!

2025-01-13 04:45 UTC, Abhishek-Jain-1925 commented on app/src/components/AiCruitForm.tsx
> +                    accept=".txt,.docx,.pdf"
As per instructions it only accepting .txt,.docx,.pdf files

2025-01-13 04:47 UTC, Abhishek-Jain-1925 commented on service/conversation_diarization/jd_interview_aligner.py
> +    sheet_name = "Java"
Currently we are using excel file here to get question bank later we are going to integrate database. Will add this path in .env file

2025-01-13 04:48 UTC, Abhishek-Jain-1925 commented on service/conversation_diarization/jd_interview_aligner.py
> +    file_path = "/Users/sethupathiasokan/Documents/AiCruit/lingo.ai/Scorecard Template.xlsx"
Currently we are using excel file here to get question bank later we are going to integrate database. 
So for now, will add this path in the .env file

2025-01-13 04:54 UTC, Abhishek-Jain-1925 commented on service/conversation_diarization/jd_interview_aligner.py
> +    file_path = "/Users/sethupathiasokan/Documents/AiCruit/lingo.ai/Scorecard Template.xlsx"
Added path in a .env file

2025-01-13 05:11 UTC, Abhishek-Jain-1925 commented on app/src/components/AiCruitForm.tsx
> +  const [checked, setChecked] = useState(false);
Done!

2025-01-13 05:24 UTC, Abhishek-Jain-1925 commented on app/src/Validators/register.ts
Done!

2025-01-13 05:34 UTC, Abhishek-Jain-1925 commented on app/migrations/0008_sudden_switch.sql
> +	"impact" text,
Done!

2025-01-17 12:15 UTC, closed without merging